# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.9.1";
  cfVersion = "v0.1.0";
  ddnsVersion = "v0.0.0-20241025234131-7c818ab3fc34";
  vendorHash = "";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.9.1";
    hash = "sha256-28ahonJ0qeynoqf02gws0LstaL4E08dywSJ8s3tgEDI=";
  };
}
