# This file was autogenerated. DO NOT EDIT!
{
  version = "v2.11.6";
  cfVersion = "v0.2.4";
  ddnsVersion = "v0.0.0-20260805195708-67d107a42c02";
  vendorHash = "";
  dist = {
    owner = "caddyserver";
    repo = "dist";
    rev = "v2.11.6";
    hash = "";
  };
}
