#!/usr/bin/env -S nix shell -I nixpkgs=./. nixpkgs#bash nixpkgs#common-updater-scripts nixpkgs#git nixpkgs#go nixpkgs#jq nixpkgs#nix-prefetch-github nixpkgs#nix-prefetch-git nixpkgs#nix-prefetch-scripts -c bash

ROOT_DIR="$(pwd)"

git_push() {
    (
        cd "$ROOT_DIR" || return
        git config --global user.name 'Updater'
        git config --global user.email 'robot@nowhere.invalid'
        git remote update

        git add flake.lock
        git add flake.nix
        git add caddy-src
        git add nix/info.nix

        git commit -m "$1"
        git push
    )
}

updateInfo() {
    version=$(sed -n 's#.*github.com/caddyserver/caddy/v2 \(.*\)#\1#p' "$ROOT_DIR/caddy-src/go.mod")
    cfVersion=$(sed -n 's#.*github.com/caddy-dns/cloudflare \(.*\)#\1#p' "$ROOT_DIR/caddy-src/go.mod")
    ddnsVersion=$(sed -n 's#.*github.com/mholt/caddy-dynamicdns \(.*\)#\1#p' "$ROOT_DIR/caddy-src/go.mod")
    dist_hash=$(nix-prefetch-github caddyserver dist --rev "$version" | jq -r .hash)

    {
        echo '# This file was autogenerated. DO NOT EDIT!'
        echo '{'
        echo "  version = \"$version\";"
        echo "  cfVersion = \"$cfVersion\";"
        echo "  ddnsVersion = \"$ddnsVersion\";"
        echo "  vendorHash = \"$1\";"
        echo "  dist = {"
        echo "    owner = \"caddyserver\";"
        echo "    repo = \"dist\";"
        echo "    rev = \"$version\";"
        echo "    hash = \"$dist_hash\";"
        echo "  };"
        echo '}'
    } >"$ROOT_DIR/nix/info.nix"
}

(
    nix flake update

    cd ./caddy-src || return
    old_hash="$(sha256sum ./go.sum)"

    rm go*
    go mod init caddy
    go mod tidy

    new_hash="$(sha256sum ./go.sum)"

    if [ "$old_hash" != "$new_hash" ]; then
        updateInfo ""
        new_vendor_hash="$(nix build ../.# |& sed -n 's/.*got: *//p')"

        updateInfo "$new_vendor_hash"

        git_push "ci: caddy and deps bumped"
    else
        echo "Up to date"
        git_push "chore: update flake.lock"
    fi
)
